version: "3.7"
services:
  minio:
    restart: always
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: darklorian
      MINIO_ROOT_PASSWORD: 36PRIMELor00
    command: server /export --console-address :9001
  backend:
    restart: always
    build: .
    ports:
      - "8000:8000"
